services:
  sd:
    build: .
    image: stable-diffusion
    ports:
      - "7860:7860"
    volumes:
      - ./sd-output:/output
      - ./sd-data:/data
      - sd-cache:/root/.cache
    environment:
      - APP_MAIN_FILE=txt2img_gradio.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  sd-cache:
